import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { NavigationProvider } from "@/context/NavigationContext";
import ToastProvider from "@/components/common/ToastProvider";
import NavigationLoader from "@/components/common/NavigationLoader";
// Import toast utility to make it available globally
import "@/utils/toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#1C1C1C] antialiased`}
        suppressHydrationWarning
      >
        <AuthProvider>
          <NavigationProvider>
            <ToastProvider />
            <NavigationLoader />
            {children}
          </NavigationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
